name: sample-ci-jobs

on:
  push:
    branches: [ jobs ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('./pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        working-directory: .
        run: mvn clean install
  
  docker_build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Build docker image
        uses: docker://docker:dind
        with:
          args: build . -t ${{ secrets.AWS_ECR_REGISTRY }}/sample-jobs:v1
    
  docker_push:
    runs-on: ubuntu-latest
    needs: docker_build
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Publish docker image
        uses: docker://docker:dind
        with:
          args: push ${{ secrets.AWS_ECR_REGISTRY }}/sample-jobs:v1